### PR TITLE
Merge monolith/aiodocker into aiodocker

### PR DESCRIPTION
**Pull request by trivigy**
I am just opening a work in progress pull request. I have been doing some major remodeling and wanted you to have an ability to look at all the changes I making so that you will be on board with them. This is definitely shifting quiet a lot from the way you originally designed it and I am taking in more inspiration from docker-py but with all asyncio capabilities. Currently I partially implemented the Image API stuff and moving forward towards the Container API. Once the container api is complete I'll make sure that all your original unittests pass so that the library will be backwards compatible but I also really want to have a discussion around how you foresee the interface. This way we could coordinate between what I want and what you want. Also note that you will only see one commit. This is because I am developing the entire thing within a monolithic repository and currently have issues exporting commit history without mingling it with history of other projects we are developing on our end. Just keep me posted with any remarks you have and we can talk them out.

One more remark. I removed your pytest stuff because I am just not very familiar with pytest but I am pretty good with python's builtin unittest module. Also I removed some of the other files like travis-ci since I am also fully familiar with how to use those. At a slightly later stage I'll make sure to setup a different CI tool or read up on travis ci and make sure that it will work well with the unittest module an the unittests I am writing.

### CODE REVIEW

**Comment by trivigy** [comment]
The BUILD file is due to my internal monolithic build system. We use bazel to run builds with a pex bundler and that's why that file is there. We can remove it from the public version of this library.

**Comment by trivigy** [comment]
Added a working version of the container functionalities but did not yet finish all the unittests for both image and container functions. Once I am done with the unittests, the next step will be to actually make it backward compatible with the functions you previously had like "image.run()" and make sure the new design passes your previous unittests

**Comment by paultag** [comment]
:+1: thank you!

**Comment by trivigy** [comment]
Replaces your jsonstream with semi-kinda version of StreamReader() to allow functionalities like containers.logs() to work when the user wants to return the stream.

**Comment by trivigy** [comment]
@paultag Sorry for the delays. I got really busy with some of my own work and what I had built here was enough for me to keep moving on with my own system. I'll circle back to this really soon.

**Comment by trivigy** [comment]
Okay I might have been quiet ambitious. I ended up basically building a different library. I have added network api support and have been trying to backward campat to your and hmmm... this is taking tons of time.

**Pull request closed without merging**
